---

- name: "{{ name }} get the pacemaker version"
  set_fact:
    pacemaker_version: "{{ ansible_facts.packages['pacemaker'][0].version }}"
  delegate_facts: true
  when: "'pacemaker' in ansible_facts.packages"

- name: "{{ name }} compare pacemaker versions across nodes"
  import_role:
    name: load_facts
    tasks_from: compare
  vars:
    fact_to_compare: "{{ pacemaker_version }}"
    config_updated: "{{ config_updated }}"

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{ pacemaker_version is defined and config_updated is not changed }}"
