---

- name: "{{ name }}.check"
  assert:
    that:
      - "'pacemaker' in ansible_facts.packages"
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='ansible_facts.packages[\'pacemaker\'][0]') | list | unique | length }} == 1"
    quiet: true
  loop: "{{ group_names }}"
  register: config_updated
  changed_when: config_updated.failed
  when: "'pacemaker' in ansible_facts.packages"

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{ config_updated is not changed }}"
