---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{'sbd' in ansible_facts.packages and ansible_facts.packages['sbd'][0].version is version(expected[name], '>') }}"
