---

- name: "{{ name }}.check"
  shell: |
    #  HANA and SPS versions are compatible
    sid=$(sudo crm configure show | grep -m1 SID= | sed -e "s/.*SID=\(...\).*/\1/" | tr '[:upper:]' '[:lower:]')
    full_version=$(sudo -i -u ${sid}adm HDB version | grep "version:" | sed -e "s/^.*:[\ ]*//")
    if [[ "$full_version" = "" ]]; then
      echo "0"
    else
      echo "$full_version"
    fi
  register: hdb_version
  check_mode: false
  changed_when: false
  failed_when: hdb_version.rc > 0

- name: "{{ name }}.check"
  assert:
    that:
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='hdb_version') | list | unique | length }} == 1"
    quiet: true
  loop: "{{ group_names }}"
  register: config_updated
  changed_when: config_updated.failed

- block:
    - name: Post results
      import_role:
        name: post-results
  vars:
    status: "{{ config_updated is not changed }}"
