name: Rebuild trento in obs
on: [push]
env:
  PACKAGE_NAME: trento
  OBS_USER: ${{ secrets.OBS_USER }}
  OBS_PASS: ${{ secrets.OBS_PASS }}
  OBS_PROJECT: ${{ secrets.OBS_PROJECT}}
  TARGET_PROJECT: ${{ secrets.TARGET_PROJECT}}
  FOLDER: packaging/suse
  GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validation:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OAUTH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: prepare changes file
      run: |
        echo "Prepare changes file"
        VERSION=$(hack/get_version_from_git.sh)
        echo "VERSION=$VERSION"
        echo $GITHUB_OAUTH_TOKEN
        .ci/gh_release_to_obs_changeset.py aleksei-burlakov/trento \
           -a shap-staff@suse.de \
           -t a730bfbb6c9ab1be602d20ad3871509310a3a7c6 \
           -f foo.changes
        find . -name foo.changes
        cat $(find . -name foo.changes)

  delivery:
    needs: validation
    runs-on: ubuntu-18.04
    if: ${{ github.event_name != 'pull_request' }}
    container:
      image: shap/continuous_deliver
      env:
        OBS_UNSTABLE: https://download.opensuse.org/repositories/OBS:/Server:/Unstable/SLE_15_SP3/OBS:Server:Unstable.repo
        OBS_UNSTABLE_KEY: https://download.opensuse.org/repositories/OBS:/Server:/Unstable/SLE_15_SP3/repodata/repomd.xml.key
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: configure OSC
    # OSC credentials must be configured beforehand as the HOME variables cannot be changed from /github/home
    # that is used to run osc commands
      run: |
        /scripts/init_osc_creds.sh
        mkdir -p $HOME/.config/osc
        cp /root/.config/osc/oscrc $HOME/.config/osc
    - name: update go and install obs-service-node_modules
      run: |
        rpm --import ${OBS_UNSTABLE_KEY}
        zypper ar ${OBS_UNSTABLE}
        zypper ref
        zypper in -y obs-service-node_modules go
        go version
    - name: deliver package
      run: |
        VERSION=$(hack/get_version_from_git.sh)
        sed -i 's~%%REVISION%%~${{ github.sha }}~' $FOLDER/_service && \
        sed -i 's~%%REPOSITORY%%~${{ github.repository }}~' $FOLDER/_service && \
        sed -i 's~%%VERSION%%~${ VERSION }~' $FOLDER/_service && \
        cp $FOLDER/_service . && \
        /scripts/upload.sh

  submit:
    needs: delivery
    runs-on: ubuntu-18.04
    if: ${{ github.event_name != 'pull_request' }}
    container:
      image: shap/continuous_deliver
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: configure OSC
      run: |
        /scripts/init_osc_creds.sh
        mkdir -p $HOME/.config/osc
        cp /root/.config/osc/oscrc $HOME/.config/osc
    - name: submit package
      run: |
       VERSION=$(hack/get_version_from_git.sh)
       sed -i 's~%%REVISION%%~${{ github.sha }}~' $FOLDER/_service && \
       sed -i 's~%%REPOSITORY%%~${{ github.repository }}~' $FOLDER/_service && \
       sed -i 's~%%VERSION%%~${VERSION}~' $FOLDER/_service && \
       cp $FOLDER/_service . && \
       /scripts/submit.sh
