name: Rebuild trento in obs
on: [push]
env:
  PACKAGE_NAME: trento
  OBS_USER: ${{ secrets.OBS_USER }}
  OBS_PASS: ${{ secrets.OBS_PASS }}
  OBS_PROJECT: ${{ secrets.OBS_PROJECT}}
  TARGET_PROJECT: ${{ secrets.TARGET_PROJECT}}
  FOLDER: packaging/suse
  GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  TAG: 0.3.0
jobs:
  validation:
    runs-on: ubuntu-18.04
    env:
      GITHUB_OAUTH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: prepare changes file
      run: |
        echo "Prepare changes file"
        VERSION=$(hack/get_version_from_git.sh)
        echo "VERSION=$VERSION"
        echo $GITHUB_OAUTH_TOKEN
        .ci/gh_release_to_obs_changeset.py $REPOSITORY \
           -a shap-staff@suse.de \
           -t $TAG  \
           -f $FOLDER/trento.changes

